Adds sleep for 10 seconds before grabbing release, failing after three tries.

diff --git a/.github/workflows/build-linux-arm64.yml b/.github/workflows/build-linux-arm64.yml
--- a/.github/workflows/build-linux-arm64.yml
+++ b/.github/workflows/build-linux-arm64.yml
@@ -1,4 +1,4 @@
-﻿name: Build 🡢 Publish 🡢 Release (Linux Arm64)
+﻿name: Build Release & VirusTotal Scan (Linux Arm64)
 
 permissions:
   contents: write
@@ -97,7 +97,16 @@ jobs:
         run: |
           DL_LINK=https://github.com/soyfrien/IpFilterGenerator/releases/download/v${{ env.VERSION }}/IpFilterConsole-${{ matrix.runtime }}.zip
           VT_LINK=${{ steps.vt_linux.outputs.permalink }}
-          wget -O ./IpFilterConsole-${{ matrix.runtime }}.zip $DL_LINK
+            for i in {1..3}; do
+                sleep 10
+                wget -O ./IpFilterConsole-${{ matrix.runtime }}.zip "$DL_LINK" && break
+                echo "Attempt $i failed. Retrying..."
+            done
+
+            if [ ! -f ./IpFilterConsole-${{ matrix.runtime }}.zip ]; then
+                echo "Download failed after 3 attempts."
+                exit 1
+            fi
 
       - name: VirusTotal Scan
         id: vt_linux
